### ISSUE TITLE
Add degrees/radians switch

### ISSUE THREAD

**Issue by terencode** [lirios/calculator#18]
Liri Calculator is radian-only.

**Comment by pierremtb** [comment]
![capture](https://cloud.githubusercontent.com/assets/10795683/25418503/a2c9b1d2-2a4c-11e7-9290-f57788f88eb1.PNG)

I'm pretty sure it's not :)

**Comment by terencode** [comment]
Cheater! :p

**Comment by pierremtb** [comment]
I agree thought that I need to find a way to help people understand its capabilities.
The help button in the advanced view leads there http://mathjs.org/docs/expressions/syntax.html

**Comment by terencode** [comment]
Would there at least be a way to choose the default mode?

**Comment by pierremtb** [comment]
There is no "default" mode

**Comment by pierremtb** [comment]
This is how MathJS works, I'm affraid I can't do nothing about it

**Comment by terencode** [comment]
Ah so that's what the documentation would rely on.

**Comment by terencode** [comment]
Ok thanks.
