### ISSUE TITLE
Fix window problems and add title

### ISSUE THREAD

**Issue by plfiorini** [lirios/calculator#9]
![screenshot from 2017-03-18 13-27-38](https://cloud.githubusercontent.com/assets/843710/24073588/dc658310-0bf9-11e7-952e-c8918b72aa95.png)

Looks like some buttons are missing and I cannot resize the window.

**Comment by plfiorini** [comment]
Also the title should be Calculator

**Comment by pierremtb** [comment]
- [x] Fix blue header bug
- [x] Add "Calculator" title
- [ ] Fix misbehaving of window resizing on Linux
